### ISSUE TITLE
Hotswap handle interrupt triggers both Rising and Falling edge status registers

### ISSUE THREAD

**Issue by henrique-silva** [lnls-dig/openMMC#17]
The Hotswap Handle pin is configured as a GPIO interruption to trigger on both Rising and Falling edges.
When the handle is closed/opened, the interruption occurs correctly, but the Chip_GPIOINT_GetStatusFalling() and Chip_GPIOINT_GetStatusRising() functions return the same value always ( 1 << 13 ) , like the handle triggered both edges at once.

The documentation of these functions says they should return `Pins that has detected falling/rising edge`

Could this be a bouncing issue?

A workaround to this problem would be to store the last known state of the handle and compare to the actual reading of the pin.

**Comment by Palmitoxico** [comment]
This certainly is a bouncing issue. AFCv3 and AFCv4 both don't have any hardware debounce circuitry, so software debouncing should be used (as it is done now). Using interrupts for this doesn't bring any advantage.
