### ISSUE TITLE
Update bootloader using the firmware update region (self-update)

### ISSUE THREAD

**Issue by augustofg** [lnls-dig/openMMC#211]
The old bootloader didn't support self-update, so we write the new bootloader image directly to the bootloader region. This is no longer necessary and somewhat dangerous, if the upload fails in the middle we end with a corrupted bootloader and if the MMC is rebooted, it will brick. Change the LPC17xx HPM low level implementation to use the firmware update area for bootloader images and correctly writing the `fw_update_header` with `fw_type` set to ~`0`~ `2`.

Remove all `memory_area area` references, always write to the firmware update region.

Change this function to accept `fw_type` as an argument:
https://github.com/lnls-dig/openMMC/blob/3b7ae353018cbc15eb9325241074fbee9fe98cb3/port/ucontroller/nxp/lpc17xx/lpc17_hpm.c#L233-L265

Make `bootloader_hpm_activate_firmware` call `ipmc_hpm_activate_firmware`
https://github.com/lnls-dig/openMMC/blob/3b7ae353018cbc15eb9325241074fbee9fe98cb3/port/ucontroller/nxp/lpc17xx/lpc17_hpm.c#L267-L279

**Comment by gustavosr8** [comment]
> Change the LPC17xx HPM low level implementation to use the firmware update area for bootloader images and correctly writing the `fw_update_header` with `fw_type` set to `0`.

The bootloader `fw_type` must be 2, as defined here:

https://github.com/lnls-dig/openMMC/blob/3b7ae353018cbc15eb9325241074fbee9fe98cb3/port/ucontroller/nxp/lpc17xx/bootloader/src/main.c#L35C6-L39
