### ISSUE TITLE
Use Continuous Integration tool (Travis CI)

### ISSUE THREAD

**Issue by henrique-silva** [lnls-dig/openMMC#42]
Since our application needs to build and test against multiple ports, we should use a CI tool to automate the tests on each commit

**Comment by aylons** [comment]
Also, we should implement unit tests for all modules.

2016-06-17 10:55 GMT-03:00 Henrique A. Silva <notifications@github.com>:

**Comment by henrique-silva** [comment]
Implemented initial integration tests with Travis CI in 3a45832f07ebc0de6a8170f2f47488dfe0eb0ff1

**Comment by Palmitoxico** [comment]
CI is already working, although no sophisticated tests are done (it only checks if the revision builds for all supported platforms and automates binary releases).

I'll close this issue for now, we are planning to move CI to github actions as Travis CI is no longer offering free builds for open source projects.
