### ISSUE TITLE
SCANSTA SCN_RSTn pin should be set as input.

### ISSUE THREAD

**Issue by abyszuk** [lnls-dig/openMMC#46]
There is a bug in the AFC/AFCK schematics.
SCN_RSTn line is connected to TRISTb pin (not TRSTb!!!) which is an *output*, not a reset input. Quoting the datasheet:
"TRI-STATE NOTIFICATION OUTPUT: This signal is asserted high when the associated TDO is
TRI-STATEd. Associated means TRISTB is for TDOB, TRIST1 is for TDO1, etc. This output has
12mA of drive current."
This means that when you drive it high, most probably you have two drivers forcing different voltage levels on one wire.

**Comment by henrique-silva** [comment]
Yes, the component actually is wrong on the schematics.
I'll open an issue on the AFC-Hardware repository and change this pin direction on the firmware.
Thanks!
