### ISSUE TITLE
Use openOCD as an alternative to program the LPC controller

### ISSUE THREAD

**Issue by henrique-silva** [lnls-dig/openMMC#79]
We should avoid using commercial software to program our board, since it limits us in terms of flexibility.
A great option is to use openOCD as an interface working together with a USB-Serial converter (FTDI, Buspirate, etc) to program the chip.

**Comment by jordens** [comment]
For reference, on Sayma-AMC we have been looking into this a bit: https://github.com/m-labs/sinara/issues/448

**Comment by sbourdeauducq** [comment]
It pretty much works out of the box, except for standard fare JTAG connection flimsiness. Here's the script I'm using:
```
source /usr/share/openocd/scripts/interface/ftdi/olimex-arm-usb-tiny-h.cfg
source /usr/share/openocd/scripts/target/lpc17xx.cfg
adapter_khz 100

program Downloads/lpc_1776_ethernet.axf verify
reset
exit
```
