### ISSUE TITLE
Fix Travis-CI build script

### ISSUE THREAD

**Issue by henrique-silva** [lnls-dig/openMMC#89]
The firmware compilation itself is running properly, but there's an error when trying to release the docs to github.io (gh-pages branch)

A good option to debug the travis errors without polluting even more the master history is to use the [Travis debug container](https://docs.travis-ci.com/user/common-build-problems/#Troubleshooting-Locally-in-a-Docker-Image)

**Comment by augustofg** [comment]
Not applicable anymore, we migrated to GitHub Actions.
