### ISSUE TITLE
event_receiver_addr should be MCH_ADDRESS

### ISSUE THREAD

**Issue by umairsiddiqui-digitek** [lnls-dig/openMMC#92]
https://github.com/lnls-dig/openMMC/blob/f11f542f4ac210cefd857bb082a86c410e434fba/modules/sdr.c#L236

i think this line should be 

`event_receiver_addr = MCH_ADDRESS;`

**Comment by henrique-silva** [comment]
It could be, but I left it as unspecified on purpose, as the IPMI standard requires the MCH to send a `Set Event Receiver` request to the MMCs upon initialization. 
This way we only send events if the MCH actively requested us to do it (by setting the event receiver address)

**Comment by henrique-silva** [comment]
On second though, it's safer to just set this address before than depending on the MCH to actively set it.
Fixed on 6a6725f9e27a8b794b00ac63405ffe1b1468f5ca
