### ISSUE TITLE
'Get FRU LED Properties command' issue

### ISSUE THREAD

**Issue by tpeshkin** [lnls-dig/openMMC#94]
Hi Henrique,

Looks like 'General Status LED Properties' byte in command is not aligned with PICMG 3.0:

<pre>
General Status LED Properties
A bit field indicating the FRU’s ability to control the four LEDs defined in
Section 2.2.8.1, “General status LEDs.” When a bit is set, the FRU can
control the associated LED.
Bit LED Name
[7:4] Reserved, is set to 0.
[3] LED 3
[2] LED 2
[1] LED 1
[0] BLUE LED
</pre>

LED module returns leds count:

https://github.com/lnls-dig/openMMC/blob/372fdbbf9ecb69d8dba055a2b0f2951c7e3cc3ed/modules/led.c#L370

**Comment by henrique-silva** [comment]
True, this needs to set the bitfield, I'll implement it in a separate branch soon.
Thanks!
