### ISSUE TITLE
Merge AFC boards ports

### ISSUE THREAD

**Issue by henrique-silva** [lnls-dig/openMMC#96]
Both AFC-BPM and AFC-Timing have extremely similar firmwares, the only difference being the clock switch (ADN4604) configuration. Even the hardware configuration is the same.

Since the FRU information is now available and parseable, we could read the board part-number in order to detect the board type and correctly configure it on runtime. 

This would avoid having 2 unnecessary copies of the same port and increase maintainability.

**Comment by Palmitoxico** [comment]
The clock switch configuration should be stored in the EEPROM and configured via IPMI, so we avoid having to hard-code these in the MMC firmware. #123
