### ISSUE TITLE
feature: writing runtime fru info EEPROM as default FRU

### ISSUE THREAD

**Issue by umairsiddiqui-digitek** [lnls-dig/openMMC#99]
when the FRU EEPROM doesn't contain valid FRU entries, then on every Reboot MMC creates Runtime FRU info.

https://github.com/lnls-dig/openMMC/blob/4a8b0c5db198fc0740ccb43d55240fc30cd0208e/modules/fru.c#L74-L80

I was wondering this Runtime FRU is written back into FRU EEPROM as a default FRU info:
```
    /* Read FRU info Common Header */
    if ( !fru_check_integrity(id, &fru[id].fru_size) ) {
        /* Could not access the SEEPROM, create a runtime fru info */
        printf("Could not find a valid FRU information in EEPROM, building a runtime info...\n");
        fru[id].fru_size = fru[id].cfg.build_f( &fru[id].buffer );
        printf(" Writing FRU info to EEPROM... \n");
        fru[id].cfg.write_f( fru[id].cfg.eeprom_id, 0x00, fru[id].buffer, fru[id].fru_size, 10 );
        fru[id].runtime = true;
    } 
```

On subsequent reboot Runtime FRU is not generated, instead the (default) FRU info is read from EEPROM.

**Comment by gustavosr8** [comment]
With the [0d92916](https://github.com/lnls-dig/openMMC/commit/0d9291663b3c0a4280c4b3cacbd2bf4b4bfeca55) commit, you can use ipmi functions to save the generated FRU in EEPROM.
